go_import_path: github.com/theMattCode/go-binance

language: go

go:
  - "1.12.x"

script:
  - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
